import assert from "node:assert/strict";
import { readFile } from "node:fs/promises";
import test from "node:test";
import { runInNewContext } from "node:vm";
const app = await readFile(new URL("../crmcabana/app.js", import.meta.url), "utf8");
const source = app.slice(app.indexOf("function financialTransactionColumnVisibility()"), app.indexOf("function renderFinancialEntryPagination(table)"));
test("column preferences survive redraws and apply only to transactions", () => {
  const state = { view: "financeTransactions", appPreferences: {} };
  const headers = Array.from({ length: 8 }, () => ({}));
  const row = { dataset: { financialEntryId: "1" }, cells: Array.from({ length: 8 }, () => ({})) };
  const summary = { dataset: {}, cells: [{}] };
  const inputs = ["notes", "category"].map((key) => ({ dataset: { financialColumn: key } }));
  const table = { querySelectorAll: () => headers, tBodies: [{ rows: [row, summary] }] };
  const apply = runInNewContext(source + "\napplyFinancialTransactionColumns", { state, document: { querySelectorAll: () => inputs } });
  apply(table);
  assert.equal(row.cells[3].hidden, true);
  assert.equal(headers[3].hidden, true);
  assert.equal(summary.cells[0].colSpan, 7);
  state.appPreferences.financialTransactionColumns = { notes: true, category: false };
  apply(table);
  assert.equal(row.cells[3].hidden, false);
  assert.equal(row.cells[4].hidden, true);
  assert.equal(inputs[0].checked, true);
  row.cells = Array.from({ length: 8 }, () => ({}));
  apply(table);
  assert.equal(row.cells[4].hidden, true);
  state.view = "financePayables";
  apply(table);
  assert.ok(row.cells.every((cell) => !cell.hidden));
  assert.equal(summary.cells[0].colSpan, 8);
});
